import org.kelvinho.graph2d.Color;
import org.kelvinho.graph2d.Graph2D;
import org.kelvinho.graph2d.geometries.Point;
import processing.core.PApplet;
import processing.event.MouseEvent;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library extends PApplet {

    private Graph2D graph2D;

    public static void main(String[] args) {
        PApplet.main("Library");
    }

    public void settings() {
        size(600, 600);
    }

    public void setup() {
        graph2D = new Graph2D(this, 600, 600);
        graph2D.addPoint(new Point(2, 2), Color.color(255, 0, 0));
    }

    public void draw() {
        graph2D.drawFrame();
        graph2D.mouse(mousePressed, mouseX, mouseY);
    }

    @Override
    public void mouseWheel(MouseEvent event) {
        graph2D.rollMouse(event.getCount());
    }

    /*
    public boolean someLibraryMethod() {
        return true;
    }/**/
}
